### ISSUE TITLE
Closure compiler throws warning "goog.array.clear does not match formal parameter" for prestans.types.Array

### ISSUE THREAD

**Issue by devraj** [anomaly/prestans-client-closure#48]
```
prestans/types/Array.js:400: WARNING - actual parameter 1 of goog.array.clear does not match formal parameter
found   : Array
required: (IArrayLike<?>|null)
    goog.array.clear(this.elements_);
```

- Compiler was built today 11th Feb 2016.
- Closure library updated as well
- Message was captured when compiling helsal

**Comment by BradMclain** [comment]
Can't seem to reproduce this specific problem. Maybe there has been another patch to closure since.

Did some some more annotation for `prestans.types.Array` anyway.
